name: pyutils tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test-py38:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: '3.8'
          - name: Install test dependencies
            run: pip install tox
          - name: Run tests
            run: tox -e py38

    test-py39:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
                python-version: '3.9'
          - name: Install test dependencies
            run: pip install tox
          - name: Run tests
            run: tox -e py39

    test-py310:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.10
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - name: Install test dependencies
          run: pip install tox
        - name: Run tests
          run: tox -e py310

    test-py311:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
        - name: Install test dependencies
          run: pip install tox
        - name: Run tests
          run: tox -e py311

    test-py312:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'
        - name: Install test dependencies
          run: pip install tox
        - name: Run tests
          run: tox -e py312
