name: pyutils type checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install test dependencies
        run: pip install tox
      - name: Run type checks
        run: tox -e type
